# Generated by Django 4.1.1 on 2022-09-25 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='NombreUsuario')),
                ('password', models.CharField(max_length=256, verbose_name='Contraseña')),
                ('name_user', models.CharField(max_length=30, verbose_name='Nombre')),
                ('email_user', models.EmailField(max_length=100, verbose_name='Correo')),
                ('create_date_user', models.DateTimeField(verbose_name='FechaCreacion')),
                ('estado_user', models.BooleanField(default=True)),
                ('apellido_user', models.CharField(max_length=30, verbose_name='Apellido')),
                ('cargo_user', models.CharField(max_length=15, verbose_name='Cargo')),
                ('direccion_user', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono_user', models.CharField(max_length=15, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id_aux', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_usuario_aux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auxiliar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_med', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_registra_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuxiliarRegistraMed', to='apphospitalbk.auxiliar')),
                ('id_usuario_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioMedico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_pac', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_registra_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuxiliarRegistraPac', to='apphospitalbk.auxiliar')),
                ('id_usuario_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioPaciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_sgv', models.BigAutoField(primary_key=True, serialize=False)),
                ('satOxigeno_sgv', models.CharField(max_length=30, verbose_name='Saturacion de Oxigeno')),
                ('presion_sgv', models.CharField(max_length=30, verbose_name='Presion')),
                ('freCardiaca_sgv', models.CharField(max_length=30, verbose_name='Frecuencia Cardiaca')),
                ('create_date_sgv', models.DateTimeField(verbose_name='Fecha Registro')),
                ('id_paciente_sgv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PacienteSGV', to='apphospitalbk.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoPaciente',
            fields=[
                ('id_medpac', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaIni_medpac', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('fechaFin_medpac', models.DateTimeField(verbose_name='Fecha Fin')),
                ('id_medico_medpac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicoMedPAC', to='apphospitalbk.medico')),
                ('id_paciente_medpac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PacienteMedPac', to='apphospitalbk.paciente')),
                ('id_registra_medpac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuxiliarRegistraMedPac', to='apphospitalbk.auxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_hc', models.BigAutoField(primary_key=True, serialize=False)),
                ('observaciones_hc', models.CharField(max_length=200, verbose_name='obeservaciones')),
                ('create_date_hc', models.DateTimeField(verbose_name='Fecha Registro')),
                ('activo_hc', models.BooleanField(default=True)),
                ('id_paciente_hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PacienteHC', to='apphospitalbk.paciente')),
            ],
        ),
    ]
