from .signosvitalesSerializer import SignosVitalesSerializer
from .pacienteSerializer import PacienteSerializer
from .medicoSerializer import MedicoSerializer
from .medico_pacienteSerializer import MedicoPacienteSerializer
from .historia_clinicaSerializer import HistoriaClinicaSerializer
from .auxiliarSerializer import AuxiliarSerializer
from .usuarioSerializer import UsuarioSerializer